import logging
from typing import List
from .data import load_json_data, data

_IGNORABLE_LOCATIONS = frozenset({
    # unimplemented
    "HIDDEN_ITEM_TRICK_HOUSE_NUGGET",
    "NPC_GIFT_RECEIVED_NATIONAL_POKEDEX",
    "NPC_GIFT_RECEIVED_POKENAV",
})

_IGNORABLE_WARPS = frozenset({
    # intro truck
    "MAP_INSIDE_OF_TRUCK:0,1,2/MAP_DYNAMIC:-1!",

    # Trick House
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE2:0,1/MAP_ROUTE110_TRICK_HOUSE_ENTRANCE:2!",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE2:2/MAP_ROUTE110_TRICK_HOUSE_END:0!",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE3:0,1/MAP_ROUTE110_TRICK_HOUSE_ENTRANCE:2!",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE3:2/MAP_ROUTE110_TRICK_HOUSE_END:0!",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE4:0,1/MAP_ROUTE110_TRICK_HOUSE_ENTRANCE:2!",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE4:2/MAP_ROUTE110_TRICK_HOUSE_END:0!",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE5:0,1/MAP_ROUTE110_TRICK_HOUSE_ENTRANCE:2!",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE5:2/MAP_ROUTE110_TRICK_HOUSE_END:0!",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE6:0,1/MAP_ROUTE110_TRICK_HOUSE_ENTRANCE:2!",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE6:2/MAP_ROUTE110_TRICK_HOUSE_END:0!",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:0,1/MAP_ROUTE110_TRICK_HOUSE_ENTRANCE:2!",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:10/MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:9",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:11/MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:12",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:12/MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:11",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:2/MAP_ROUTE110_TRICK_HOUSE_END:0!",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:3/MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:4",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:4/MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:3",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:5/MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:6",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:6/MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:5",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:7/MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:8",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:8/MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:7",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:9/MAP_ROUTE110_TRICK_HOUSE_PUZZLE7:10",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE8:0,1/MAP_ROUTE110_TRICK_HOUSE_ENTRANCE:2!",
    "MAP_ROUTE110_TRICK_HOUSE_PUZZLE8:2/MAP_ROUTE110_TRICK_HOUSE_END:0!",
    
    # Department Store elevator
    "MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F:3/MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR:0!",
    "MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F:2/MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR:0!",
    "MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F:2/MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR:0!",
    "MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F:2/MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR:0!",
    "MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F:1/MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR:0!",
    "MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR:0,1/MAP_DYNAMIC:-1!",

    # Trainer Hill
    "MAP_TRAINER_HILL_1F:0/MAP_TRAINER_HILL_ENTRANCE:2",
    "MAP_TRAINER_HILL_1F:1/MAP_TRAINER_HILL_2F:0",
    "MAP_TRAINER_HILL_2F:0/MAP_TRAINER_HILL_1F:1",
    "MAP_TRAINER_HILL_2F:1/MAP_TRAINER_HILL_3F:0",
    "MAP_TRAINER_HILL_3F:0/MAP_TRAINER_HILL_2F:1",
    "MAP_TRAINER_HILL_3F:1/MAP_TRAINER_HILL_4F:0",
    "MAP_TRAINER_HILL_4F:0/MAP_TRAINER_HILL_3F:1",
    "MAP_TRAINER_HILL_4F:1/MAP_TRAINER_HILL_ROOF:0",
    "MAP_TRAINER_HILL_ELEVATOR:0,1/MAP_TRAINER_HILL_ROOF:1",
    "MAP_TRAINER_HILL_ENTRANCE:2/MAP_TRAINER_HILL_1F:0",
    "MAP_TRAINER_HILL_ROOF:0/MAP_TRAINER_HILL_4F:1",
    "MAP_TRAINER_HILL_ROOF:1/MAP_TRAINER_HILL_ELEVATOR:1",

    # Battle Frontier
    "MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR:0,1/MAP_BATTLE_FRONTIER_OUTSIDE_WEST:1!",
    "MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM:0,1/MAP_BATTLE_FRONTIER_OUTSIDE_WEST:1!",
    "MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM:0,1/MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR:2",
    "MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR:0,1/MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY:2",
    "MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR:2/MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM:0",
    "MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR:3/MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM:0!",
    "MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY:2/MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR:0",
    "MAP_BATTLE_FRONTIER_OUTSIDE_EAST:11/MAP_BATTLE_FRONTIER_LOUNGE9:0",

    # Terra Cave and Marine Cave
    "MAP_TERRA_CAVE_ENTRANCE:0/MAP_DYNAMIC:-1!",
    "MAP_ROUTE113:1/MAP_TERRA_CAVE_ENTRANCE:0!",
    "MAP_ROUTE113:2/MAP_TERRA_CAVE_ENTRANCE:0!",
    "MAP_ROUTE114:3/MAP_TERRA_CAVE_ENTRANCE:0!",
    "MAP_ROUTE114:4/MAP_TERRA_CAVE_ENTRANCE:0!",
    "MAP_ROUTE115:1/MAP_TERRA_CAVE_ENTRANCE:0!",
    "MAP_ROUTE115:2/MAP_TERRA_CAVE_ENTRANCE:0!",
    "MAP_ROUTE116:3/MAP_TERRA_CAVE_ENTRANCE:0!",
    "MAP_ROUTE116:4/MAP_TERRA_CAVE_ENTRANCE:0!",
    "MAP_ROUTE118:0/MAP_TERRA_CAVE_ENTRANCE:0!",
    "MAP_ROUTE118:1/MAP_TERRA_CAVE_ENTRANCE:0!",

    "MAP_UNDERWATER_MARINE_CAVE:0/MAP_DYNAMIC:-1!",
    "MAP_UNDERWATER_ROUTE105:0/MAP_UNDERWATER_MARINE_CAVE:0!",
    "MAP_UNDERWATER_ROUTE105:1/MAP_UNDERWATER_MARINE_CAVE:0!",
    "MAP_UNDERWATER_ROUTE125:0/MAP_UNDERWATER_MARINE_CAVE:0!",
    "MAP_UNDERWATER_ROUTE125:1/MAP_UNDERWATER_MARINE_CAVE:0!",
    "MAP_UNDERWATER_ROUTE127:0/MAP_UNDERWATER_MARINE_CAVE:0!",
    "MAP_UNDERWATER_ROUTE127:1/MAP_UNDERWATER_MARINE_CAVE:0!",
    "MAP_UNDERWATER_ROUTE129:0/MAP_UNDERWATER_MARINE_CAVE:0!",
    "MAP_UNDERWATER_ROUTE129:1/MAP_UNDERWATER_MARINE_CAVE:0!",

    # Altering Cave
    "MAP_ROUTE103:0/MAP_ALTERING_CAVE:0",

    # Secret bases
    "MAP_SECRET_BASE_BROWN_CAVE1:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_BROWN_CAVE2:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_BROWN_CAVE3:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_BROWN_CAVE4:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_BLUE_CAVE1:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_BLUE_CAVE2:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_BLUE_CAVE3:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_BLUE_CAVE4:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_YELLOW_CAVE1:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_YELLOW_CAVE2:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_YELLOW_CAVE3:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_YELLOW_CAVE4:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_RED_CAVE1:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_RED_CAVE2:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_RED_CAVE3:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_RED_CAVE4:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_SHRUB1:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_SHRUB2:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_SHRUB3:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_SHRUB4:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_TREE1:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_TREE2:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_TREE3:0/MAP_DYNAMIC:-2!",
    "MAP_SECRET_BASE_TREE4:0/MAP_DYNAMIC:-2!",

    # multiplayer rooms
    "MAP_TRADE_CENTER:0,1/MAP_DYNAMIC:-1!",
    "MAP_RECORD_CORNER:0,1,2,3/MAP_DYNAMIC:-1!",
    "MAP_UNION_ROOM:0,1/MAP_DYNAMIC:-1!",

    "MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",
    "MAP_DEWFORD_TOWN_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",
    "MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",
    "MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F:1/MAP_UNION_ROOM:0!",
    "MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",
    "MAP_FORTREE_CITY_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",
    "MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",
    "MAP_LILYCOVE_CITY_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",
    "MAP_MAUVILLE_CITY_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",
    "MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",
    "MAP_OLDALE_TOWN_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",
    "MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",
    "MAP_PETALBURG_CITY_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",
    "MAP_RUSTBORO_CITY_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",
    "MAP_SLATEPORT_CITY_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",
    "MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",
    "MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F:1/MAP_UNION_ROOM:0!",

    "MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F:2/MAP_TRADE_CENTER:0!",
    "MAP_DEWFORD_TOWN_POKEMON_CENTER_2F:2/MAP_TRADE_CENTER:0!",
    "MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F:2/MAP_TRADE_CENTER:0!",
    "MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F:2/MAP_TRADE_CENTER:0!",
    "MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F:2/MAP_TRADE_CENTER:0!",
    "MAP_FORTREE_CITY_POKEMON_CENTER_2F:2/MAP_TRADE_CENTER:0!",
    "MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F:1/MAP_TRADE_CENTER:0!",
    "MAP_LILYCOVE_CITY_POKEMON_CENTER_2F:1/MAP_TRADE_CENTER:0!",
    "MAP_MAUVILLE_CITY_POKEMON_CENTER_2F:1/MAP_TRADE_CENTER:0!",
    "MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F:1/MAP_TRADE_CENTER:0!",
    "MAP_OLDALE_TOWN_POKEMON_CENTER_2F:1/MAP_TRADE_CENTER:0!",
    "MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F:1/MAP_TRADE_CENTER:0!",
    "MAP_PETALBURG_CITY_POKEMON_CENTER_2F:1/MAP_TRADE_CENTER:0!",
    "MAP_RUSTBORO_CITY_POKEMON_CENTER_2F:1/MAP_TRADE_CENTER:0!",
    "MAP_SLATEPORT_CITY_POKEMON_CENTER_2F:1/MAP_TRADE_CENTER:0!",
    "MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F:1/MAP_TRADE_CENTER:0!",
    "MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F:1/MAP_TRADE_CENTER:0!",

    "MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F:2/MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F:0",
    "MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F:0/MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F:2",

    "MAP_BATTLE_COLOSSEUM_2P:0,1/MAP_DYNAMIC:-1!",
    "MAP_BATTLE_COLOSSEUM_4P:0,1,2,3/MAP_DYNAMIC:-1!",

    # unused maps
    "MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1:0/MAP_CAVE_OF_ORIGIN_1F:1!",
    "MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1:1/MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2:0",
    "MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2:0/MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1:1",
    "MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2:1/MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3:0",
    "MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3:0/MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2:1",
    "MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3:1/MAP_CAVE_OF_ORIGIN_B1F:0!",
    "MAP_LILYCOVE_CITY_UNUSED_MART:0,1/MAP_LILYCOVE_CITY:0!",
})

def validate_regions() -> bool:
    extracted_data = load_json_data("extracted_data.json")
    error_msgs: List[str] = list()
    warn_msgs: List[str] = list()
    failed = False

    def error(msg: str) -> None:
        nonlocal failed
        failed = True
        error_msgs.append(msg)

    def warn(msg: str) -> None:
        warn_msgs.append(msg)

    # check regions
    for name, region in data.regions.items():
        for region_exit in region.exits:
            if region_exit not in data.regions:
                error(f"Flit's Pokemon Emerald: Region [{region_exit}] referenced by [{name}] is not defined.")

    # check warps
    for source, dest in data.warp_map.items():
        if source in _IGNORABLE_WARPS:
            continue
        if dest in _IGNORABLE_WARPS:
            continue

        if dest is None:
            error(f"Flit's Pokemon Emerald: Warp [{source}] has no destination.")
        elif not data.warps[dest].connects_to(data.warps[source]) and not data.warps[source].is_one_way:
            error(f"Flit's Pokemon Emerald: Warp [{source}] appears to be one-way, but was not marked as such.")

    # check locations
    region_locations = [location for region in data.regions.values() for location in region.locations]
    claimed_locations = set()
    for location_id in region_locations:
        if location_id in claimed_locations:
            error(f"Flit's Pokemon Emerald: Location [{location_id}] exists in multiple regions.")
        claimed_locations.add(location_id)

    for location_id in extracted_data["locations"]:
        if location_id not in claimed_locations and location_id not in _IGNORABLE_LOCATIONS:
            warn(f"Flit's Pokemon Emerald: Location [{location_id}] does not belong to any region.")

    error_msgs.sort()
    warn_msgs.sort()

    for msg in warn_msgs:
        logging.warning(msg)
    for msg in error_msgs:
        logging.error(msg)

    logging.debug("Flit's Pokemon Emerald sanity check done. Found %s warnings and %s errors.",
                  len(warn_msgs),
                  len(error_msgs)
    )

    return not failed
